# Generated by Django 5.1 on 2024-10-09 16:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0012_report_accession_number_and_study_instance_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSearchVectorNew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_vector_new",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parade_search_vector",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector_new"],
                        name="parade_sear_search__de128e_gin",
                    )
                ],
            },
        ),
    ]
