# Generated by Django 5.1 on 2024-11-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parade_search", "0001_initial"),
        ("reports", "0014_populate_language_columns"),
    ]

    operations = [
        # RunSQL to create a BM25 index on the generated columns body_en and body_de
        migrations.RunSQL(
            sql="""
                CALL paradedb.create_bm25(
                    index_name   => 'reports_report_multilang_body_idx',
                    table_name   => 'reports_report',
                    key_field    => 'id',
                    text_fields  => paradedb.field('body_en', tokenizer => paradedb.tokenizer('default', stemmer => 'English')) ||
                                    paradedb.field('body_de', tokenizer => paradedb.tokenizer('default', stemmer => 'German'))
                );
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS reports_report_multilang_body_idx;
            """
        ),
    ]
