# Generated by Django 5.1.3 on 2024-12-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parade_search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParadeDBReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_en", models.TextField(blank=True)),
                ("body_de", models.TextField(blank=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ParadeDBReport",
                        to="reports.report",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ReportSearchVectorNew",
        ),
    ]
