# Generated by Django 5.1 on 2024-11-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parade_search", "0001_initial"),
        ("parade_search", "0003_populate_language_body"),
    ]

    operations = [
        # RunSQL to create a BM25 index on the generated columns body_en and body_de
        migrations.RunSQL(
            sql="""
                CREATE INDEX reports_report_multilang_body_idx
                ON parade_search_paradedbreport
                USING bm25 (id, body_en, body_de)
                WITH (
                    key_field = 'id',
                    text_fields = '{
                        "body_en": {"tokenizer": {"type": "default", "stemmer": "English"}},
                        "body_de": {"tokenizer": {"type": "default", "stemmer": "German"}}
                    }'
                );

            """,
            reverse_sql="""
                DROP INDEX IF EXISTS reports_report_multilang_body_idx;
            """
        ),
    ]
