# Generated by Django 5.0.6 on 2024-07-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pgsearch", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ReportSearchVector",
        ),
    ]
