# Generated by Django 6.0.1 on 2026-05-15 18:19

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0002_pgvector_extension'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsearchvector',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddIndex(
            model_name='reportsearchvector',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='pgsearch_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
