# Generated by Django 6.0.7 on 2026-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0002_hybrid_search'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexemeRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexeme', models.TextField()),
                ('rank', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_ranks', to='reports.report')),
            ],
            options={
                'indexes': [models.Index(fields=['lexeme', '-rank', 'report'], name='pgsearch_lexeme_rank_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'lexeme'), name='pgsearch_lexemerank_uniq')],
            },
        ),
    ]
