# Generated by Django 6.0.1 on 2026-02-17 15:26

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0002_enable_pgvector'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingBackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('SU', 'Success'), ('FA', 'Failure')], default='PE', max_length=2)),
                ('total_reports', models.PositiveIntegerField(default=0)),
                ('processed_reports', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reportsearchvector',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name='reportsearchvector',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='pgsearch_re_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
