# Generated by Django 6.0.6 on 2026-07-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pgsearch", "0002_hybrid_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingBackfillRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("total_reports", models.PositiveIntegerField()),
                ("processed_reports", models.PositiveIntegerField(default=0)),
                ("triggered_by", models.CharField(max_length=150)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
