# Generated by Django 6.0.7 on 2026-08-30 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0002_hybrid_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsearchindex',
            name='group_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='language_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='modality_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='patient_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='patient_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='patient_sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='report_created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='report_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='study_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reportsearchindex',
            name='study_description',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
