# Generated by Django 6.0.6 on 2026-07-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0003_pending_embedding_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsearchindex',
            options={'verbose_name': 'Report search index', 'verbose_name_plural': 'Report search indexes'},
        ),
        migrations.RenameIndex(
            model_name='reportsearchindex',
            new_name='pgsearch_re_search__b0f715_gin',
            old_name='pgsearch_re_search__a80d52_gin',
        ),
    ]
