# Generated by Django 6.0.7 on 2026-08-30 20:20

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0004_search_projection_backfill'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['group_ids'], name='pgsearch_group_ids_gin'),
        ),
        migrations.AddIndex(
            model_name='reportsearchindex',
            index=models.Index(fields=['report_updated_at'], name='pgsearch_report_updated_at_idx'),
        ),
        migrations.RunSQL(
            # fastupdate leaves an unsorted pending list that every query must
            # scan; RADIS writes in async batches and reads interactively, so
            # predictable read latency is the better side of the trade.
            "ALTER INDEX pgsearch_re_search__b0f715_gin SET (fastupdate = off);"
            "SELECT gin_clean_pending_list('pgsearch_re_search__b0f715_gin');",
            reverse_sql="ALTER INDEX pgsearch_re_search__b0f715_gin SET (fastupdate = on);",
        ),
        # Recreate the embedding index 0004 dropped, from the stored vectors:
        # one bulk build instead of the per-row inserts the backfill would
        # otherwise have paid (7m36s versus ~68h measured at 1.7M vectors).
        # The build honors the server's maintenance_work_mem and
        # max_parallel_maintenance_workers -- raise them for a large embedded
        # corpus (POSTGRES_* knobs in the compose files). IF NOT EXISTS keeps
        # re-runs and installs that never dropped it safe; the definition must
        # match the HnswIndex in ReportSearchIndex.Meta. Reverse is a no-op on
        # purpose: unapplying 0005 then 0004 must leave the index present,
        # which is the state before 0005 dropped it.
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS pgsearch_embedding_hnsw "
            "ON pgsearch_reportsearchindex "
            "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            # Required, not hygiene: the projection columns and the indexes
            # above carry no statistics, and the single-table query shape
            # depends on the planner choosing a parallel sequential scan with
            # a top-N heapsort. ANALYZE is transaction-legal, so this migration stays atomic.
            "ANALYZE pgsearch_reportsearchindex;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
