# Generated by Django 6.0.6 on 2026-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0004_django6_index_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingBackoffState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paused_until', models.DateTimeField(default=None, null=True)),
                ('consecutive_429s', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Embedding backoff state',
                'verbose_name_plural': 'Embedding backoff states',
            },
        ),
    ]
