# Generated by Django 6.0.7 on 2026-08-30 20:20

import re

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


def rebuild_hnsw(apps, schema_editor):
    """Recreate the embedding index that 0005 dropped, from the stored vectors.

    One bulk build assembles the graph in maintenance_work_mem instead of the
    row-at-a-time inserts the backfill would otherwise have paid (7m36s versus
    ~68h measured at 1.7M vectors). Guarded so installs where the index still
    exists -- and re-runs -- skip it. The definition must match the HnswIndex
    in ReportSearchIndex.Meta.
    """
    memory = settings.PGSEARCH_HNSW_REBUILD_MAINTENANCE_WORK_MEM
    if not re.fullmatch(r"\d+\s*(kB|MB|GB|TB)", memory):
        raise ValueError(
            f"PGSEARCH_HNSW_REBUILD_MAINTENANCE_WORK_MEM is not a PostgreSQL "
            f"memory value: {memory!r}"
        )
    workers = int(settings.PGSEARCH_HNSW_REBUILD_PARALLEL_WORKERS)
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_indexes WHERE indexname = 'pgsearch_embedding_hnsw'")
        if cursor.fetchone():
            return
        # SET LOCAL: scoped to this migration's transaction, so nothing leaks
        # to later migrations sharing the connection.
        cursor.execute(f"SET LOCAL maintenance_work_mem = '{memory}'")
        cursor.execute(f"SET LOCAL max_parallel_maintenance_workers = {workers}")
        cursor.execute(
            "CREATE INDEX pgsearch_embedding_hnsw ON pgsearch_reportsearchindex "
            "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0005_search_projection_backfill'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['group_ids'], name='pgsearch_group_ids_gin'),
        ),
        migrations.AddIndex(
            model_name='reportsearchindex',
            index=models.Index(fields=['report_updated_at'], name='pgsearch_report_updated_at_idx'),
        ),
        migrations.RunSQL(
            # fastupdate leaves an unsorted pending list that every query must
            # scan; RADIS writes in async batches and reads interactively, so
            # predictable read latency is the better side of the trade.
            "ALTER INDEX pgsearch_re_search__b0f715_gin SET (fastupdate = off);"
            "SELECT gin_clean_pending_list('pgsearch_re_search__b0f715_gin');",
            reverse_sql="ALTER INDEX pgsearch_re_search__b0f715_gin SET (fastupdate = on);",
        ),
        # Reverse is a no-op on purpose: unapplying 0006 then 0005 must leave
        # the index present, which is the state before 0005 dropped it.
        migrations.RunPython(rebuild_hnsw, migrations.RunPython.noop),
        migrations.RunSQL(
            # Required, not hygiene: the projection columns and the indexes
            # above carry no statistics, and the single-table query shape
            # depends on the planner choosing a parallel sequential scan with
            # a top-N heapsort. ANALYZE is transaction-legal, so 0006 stays atomic.
            "ANALYZE pgsearch_reportsearchindex;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
