# Generated by Django 6.0.7 on 2026-08-30 20:20

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0005_search_projection_backfill'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['group_ids'], name='pgsearch_group_ids_gin'),
        ),
        migrations.AddIndex(
            model_name='reportsearchindex',
            index=models.Index(fields=['report_updated_at'], name='pgsearch_report_updated_at_idx'),
        ),
        migrations.RunSQL(
            # fastupdate leaves an unsorted pending list that every query must
            # scan; RADIS writes in async batches and reads interactively, so
            # predictable read latency is the better side of the trade.
            "ALTER INDEX pgsearch_re_search__b0f715_gin SET (fastupdate = off);"
            "SELECT gin_clean_pending_list('pgsearch_re_search__b0f715_gin');",
            reverse_sql="ALTER INDEX pgsearch_re_search__b0f715_gin SET (fastupdate = on);",
        ),
        migrations.RunSQL(
            # Required, not hygiene: the ten projection columns and the two
            # indexes above carry no statistics, and the single-table query
            # shape this whole change exists for depends on the planner
            # choosing a parallel sequential scan with a top-N heapsort.
            # ANALYZE is legal inside a transaction block, so this migration
            # stays atomic.
            "ANALYZE pgsearch_reportsearchindex;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
