# Generated by Django 6.0.7 on 2026-09-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0005_search_projection_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsearchindex',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
