# Generated by Django 6.0.7 on 2026-09-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgsearch', '0007_code_rename_triggers'),
        ('pgsearch', '0008_search_projection_withdrawn_trigger'),
    ]

    operations = [
    ]
