# Generated by Django 4.2.10 on 2024-03-16 13:45

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import radis.rag.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0008_modality_remove_report_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('accepted_answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RagAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'RAG app settings',
            },
        ),
        migrations.CreateModel(
            name='RagJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UV', 'Unverified'), ('PR', 'Preparing'), ('PE', 'Pending'), ('IP', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='UV', max_length=2)),
                ('urgent', models.BooleanField(default=False)),
                ('send_finished_mail', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('Keyword Search', 'Keyword Search')], max_length=100)),
                ('query', models.CharField(max_length=200)),
                ('study_date_from', models.DateField(blank=True, null=True)),
                ('study_date_till', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=200)),
                ('modalities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('patient_sex', models.CharField(blank=True, choices=[('', 'All'), ('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_from', models.IntegerField(blank=True, null=True)),
                ('age_till', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_analyze_urgently', 'Can analyze urgently')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RagTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='PE', max_length=2)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('overall_result', models.CharField(blank=True, choices=[('A', 'Accepted'), ('R', 'Rejected')], max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rag.ragjob')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_tasks', to='reports.report')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('result', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rag.question')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rag.ragtask')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='rag.ragjob'),
        ),
        migrations.AddIndex(
            model_name='ragjob',
            index=models.Index(fields=['owner', 'status'], name='rag_ragjob_owner_i_cbe4d1_idx'),
        ),
    ]
