# Generated by Django 4.2.11 on 2024-03-23 12:46

from django.db import migrations, models
import radis.rag.models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragjob',
            name='provider',
            field=models.CharField(choices=[('Vespa BM25', 'Vespa BM25')], default=radis.rag.models.get_default_provider, max_length=100),
        ),
    ]
