# Generated by Django 4.2.11 on 2024-03-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_ragjob_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionresult',
            old_name='answer',
            new_name='original_answer',
        ),
        migrations.AddField(
            model_name='questionresult',
            name='current_answer',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
