# Generated by Django 4.2.11 on 2024-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_rename_answer_questionresult_original_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
