# Generated by Django 5.0.4 on 2024-04-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_ragjob_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ragjob',
            name='language',
        ),
    ]
