# Generated by Django 5.0.4 on 2024-04-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0006_remove_ragjob_language'),
        ('reports', '0009_language_alter_report_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.language'),
            preserve_default=False,
        ),
    ]
