# Generated by Django 5.0.4 on 2024-04-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0008_remove_ragjob_modalities'),
        ('reports', '0009_language_alter_report_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='modalities',
            field=models.ManyToManyField(blank=True, to='reports.modality'),
        ),
    ]
