# Generated by Django 5.0.4 on 2024-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_ragjob_modalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragjob',
            name='provider',
            field=models.CharField(max_length=100),
        ),
    ]
