# Generated by Django 5.0.4 on 2024-04-15 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0009_ragjob_modalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='max_to_accept',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ragjob',
            name='max_to_process',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
