# Generated by Django 5.0.6 on 2024-07-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag", "0010_alter_ragjob_provider"),
        ("reports", "0010_remove_report_links_report_pacs_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionresult",
            name="task",
        ),
        migrations.RemoveField(
            model_name="ragtask",
            name="overall_result",
        ),
        migrations.RemoveField(
            model_name="ragtask",
            name="report",
        ),
        migrations.CreateModel(
            name="RagInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_result",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Accepted"), ("R", "Rejected")],
                        max_length=1,
                    ),
                ),
                ("reports", models.ManyToManyField(to="reports.report")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_instances",
                        to="rag.ragtask",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="questionresult",
            name="rag_instance",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="rag.raginstance",
            ),
            preserve_default=False,
        ),
    ]
