# Generated by Django 5.0.7 on 2024-07-21 12:54

import django.db.models.deletion
from django.db import migrations, models

from adit_radis_shared.common.utils.migration_utils import procrastinate_on_delete_sql


class Migration(migrations.Migration):

    dependencies = [
        ('procrastinate', '0028_add_cancel_states'),
        ('rag', '0011_remove_questionresult_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragtask',
            old_name='retries',
            new_name='attempts',
        ),
        migrations.RemoveField(
            model_name='ragtask',
            name='celery_task_id',
        ),
        migrations.AddField(
            model_name='ragjob',
            name='queued_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procrastinate.procrastinatejob'),
        ),
        migrations.AddField(
            model_name='ragtask',
            name='queued_job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procrastinate.procrastinatejob'),
        ),
        migrations.RunSQL(
            sql=procrastinate_on_delete_sql("rag", "ragjob"),
            reverse_sql=procrastinate_on_delete_sql("rag", "ragjob", reverse=True),
        ),
        migrations.RunSQL(
            sql=procrastinate_on_delete_sql("rag", "ragtask"),
            reverse_sql=procrastinate_on_delete_sql("rag", "ragtask", reverse=True),
        ),
    ]
