# Generated by Django 5.0.7 on 2024-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0012_switch_to_procrastinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='raginstance',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
