# Generated by Django 5.0.7 on 2024-08-04 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0013_raginstance_text'),
        ('reports', '0011_report_patient_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raginstance',
            old_name='reports',
            new_name='other_reports',
        ),
        migrations.AddField(
            model_name='raginstance',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rag_instances', to='reports.report'),
            preserve_default=False,
        ),
    ]
