# Generated by Django 5.1.3 on 2024-12-03 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_grammar'),
        ('rag', '0014_other_reports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionresult',
            name='rag_instance',
        ),
        migrations.CreateModel(
            name='AnalysisQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('grammar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.grammar')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_questions', to='rag.ragjob')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_answer', models.CharField(max_length=500)),
                ('current_answer', models.CharField(max_length=500)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rag.analysisquestion')),
                ('rag_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='rag.raginstance')),
            ],
        ),
        migrations.CreateModel(
            name='FilterQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('accepted_answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_questions', to='rag.ragjob')),
            ],
        ),
        migrations.CreateModel(
            name='FilterQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('current_answer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('result', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rag.filterquestion')),
                ('rag_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_results', to='rag.raginstance')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionResult',
        ),
    ]
