# Generated by Django 5.1.2 on 2024-11-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_grammar"),
        ("rag", "0015_remove_questionresult_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisquestion",
            name="grammar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chats.grammar"
            ),
        ),
    ]
