# Generated by Django 5.1.3 on 2024-12-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_grammar_name'),
        ('rag', '0016_alter_analysisquestion_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisquestion',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.grammar'),
        ),
    ]
