image:
  file: .gitpod.Dockerfile

tasks:
  - name: setup
    init: |
      poetry install
      poetry run ./init_workspace.py

ports:
  - port: 8000
    onOpen: notify
  - port: 6501-6502
    onOpen: ignore
  - port: 7501-7502
    onOpen: ignore
  - port: 11122
    onOpen: ignore
  - port: 5678
    onOpen: ignore

vscode:
  extensions:
    - "batisteo.vscode-django"
    - "charliermarsh.ruff"
    - "davidanson.vscode-markdownlint"
    - "eamodio.gitlens"
    - "esbenp.prettier-vscode"
    - "formulahendry.auto-close-tag"
    - "formulahendry.auto-rename-tag"
    - "foxundermoon.shell-format"
    - "grapecity.gc-excelviewer"
    - "jock.svg"
    - "mhutchie.git-graph"
    - "mikestead.dotenv"
    - "monosans.djlint"
    - "ms-azuretools.vscode-docker"
    - "ms-pyright.pyright"
    - "ms-python.python"
    - "streetsidesoftware.code-spell-checker"
    - "tamasfe.even-better-toml"
    - "wayou.vscode-todo-highlight"
    - "xabikos.javascriptsnippets"
