x-app: &default-app
  volumes:
    - ${BACKUP_DIR:?}:/backups
  depends_on:
    - postgres
  env_file:
    - .env
  environment:
    DATABASE_URL: postgres://postgres:postgres@postgres.local:5432/postgres
    DBBACKUP_STORAGE_LOCATION: /backups
    IS_DOCKER_CONTAINER: 1
    # STACK_NAME is computed by the CLI and passed as process environment variable,
    # it is not necessarily set in the .env file.
    STACK_NAME: ${STACK_NAME:-}

services:
  init:
    <<: *default-app
    hostname: init.local

  web:
    <<: *default-app
    build:
      args:
        - PROJECT_VERSION=${PROJECT_VERSION:?}
    hostname: web.local

  default_worker:
    <<: *default-app
    hostname: default_worker.local

  llm_worker:
    <<: *default-app
    hostname: llm_worker.local

  embeddings_worker:
    <<: *default-app
    hostname: embeddings_worker.local

  postgres:
    image: pgvector/pgvector:pg17@sha256:cf134a767f474095eeba57e0117be8e568e011a63f33fbf252f14c9b760f8e6f
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
