# Generated by Django 5.2.7 on 2025-11-03 22:58

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0002_procrastinate_on_delete"),
        ("subscriptions", "0008_rename_filter_fields_result_subscribeditem_answers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outputfield",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_fields",
                to="extractions.extractionjob",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="outputfield",
            name="unique_output_field_name_per_job",
        ),
        migrations.RemoveField(
            model_name="outputfield",
            name="optional",
        ),
        migrations.AddField(
            model_name="outputfield",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extraction_fields",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.UniqueConstraint(
                condition=Q(job__isnull=False),
                fields=("name", "job_id"),
                name="unique_output_field_name_per_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.UniqueConstraint(
                condition=Q(subscription__isnull=False),
                fields=("name", "subscription_id"),
                name="unique_output_field_name_per_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.CheckConstraint(
                check=(
                    Q(job__isnull=False, subscription__isnull=True)
                    | Q(job__isnull=True, subscription__isnull=False)
                ),
                name="output_field_exactly_one_parent",
            ),
        ),
    ]
