# Generated by Django 5.2.7 on 2025-11-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0002_procrastinate_on_delete"),
        ("subscriptions", "0009_alter_subscribeditem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractionjob",
            options={"ordering": ["-created_at", "title"]},
        ),
        migrations.RemoveConstraint(
            model_name="outputfield",
            name="unique_output_field_name_per_job",
        ),
        migrations.RemoveIndex(
            model_name="extractionjob",
            name="extractions_owner_i_49b05e_idx",
        ),
        migrations.RemoveField(
            model_name="outputfield",
            name="optional",
        ),
        migrations.AddField(
            model_name="outputfield",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extraction_fields",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AlterField(
            model_name="outputfield",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_fields",
                to="extractions.extractionjob",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job__isnull", False)),
                fields=("name", "job_id"),
                name="unique_output_field_name_per_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscription__isnull", False)),
                fields=("name", "subscription_id"),
                name="unique_output_field_name_per_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("job__isnull", False), ("subscription__isnull", True)),
                    models.Q(("job__isnull", True), ("subscription__isnull", False)),
                    _connector="OR",
                ),
                name="output_field_exactly_one_parent",
            ),
        ),
    ]
