# Generated by Django 5.2.7 on 2025-11-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0002_procrastinate_on_delete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractionjob",
            options={"ordering": ["-created_at", "title"]},
        ),
        migrations.RemoveIndex(
            model_name="extractionjob",
            name="extractions_owner_i_49b05e_idx",
        ),
    ]
