# Generated by Django 5.2.8 on 2025-11-17 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0003_alter_extractionjob_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="outputfield",
            name="unique_output_field_name_per_job",
        ),
        migrations.RemoveField(
            model_name="outputfield",
            name="optional",
        ),
        migrations.AlterField(
            model_name="outputfield",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_fields",
                to="extractions.extractionjob",
            ),
        ),
    ]
