# Generated by Django 5.2.8 on 2025-11-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0004_remove_outputfield_unique"),
        ("subscriptions", "0010_rename_answers_subscribeditem_filter_results_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outputfield",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="output_fields",
                to="subscriptions.subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job__isnull", False)),
                fields=("name", "job_id"),
                name="unique_output_field_name_per_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscription__isnull", False)),
                fields=("name", "subscription_id"),
                name="unique_output_field_name_per_subscription",
            ),
        ),
        migrations.AddConstraint(
            model_name="outputfield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("job__isnull", False), ("subscription__isnull", True)),
                    models.Q(("job__isnull", True), ("subscription__isnull", False)),
                    _connector="OR",
                ),
                name="output_field_exactly_one_parent",
            ),
        ),
    ]
