# Generated by Django 5.2.8 on 2025-11-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0005_outputfield_is_array"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extractionjob",
            name="provider",
        ),
    ]
