# Generated by Django 6.0 on 2025-12-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0006_outputfield_subscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionjob",
            name="query",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
