# Generated by Django 6.0.7 on 2026-08-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractions", "0006_outputfield_subscription_and_more"),
        ("reports", "0013_alter_report_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionjob",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="reports.language",
            ),
        ),
    ]
