# Generated by Django 5.2.7 on 2025-11-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-created", "name"]},
        ),
    ]
