# Generated by Django 5.0.7 on 2024-08-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxitem',
            old_name='Subscription',
            new_name='subscription',
        ),
    ]
