# Generated by Django 5.0.6 on 2024-07-12 13:07

from django.db import migrations


def vacuum_and_reindex_reports_report(apps, schema_editor):
    # Get the database connections
    connection = schema_editor.connection

    # Run VACUUM ANALYZE
    with connection.cursor() as cursor:
        cursor.execute("VACUUM ANALYZE reports_report;")

    # Run REINDEX TABLE
    with connection.cursor() as cursor:
        cursor.execute("REINDEX TABLE reports_report;")


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_report_reports_rep_search__63862e_gin"),
    ]

    operations = [
        migrations.RunSQL(
            sql="VACUUM ANALYZE reports_report; REINDEX TABLE reports_report;",
            reverse_sql="",
            state_operations=[],
            atomic=False
        ),
    ]
