# Generated by Django 5.1.4 on 2025-01-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_rename_chatssettings_chatsappsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsappsettings",
            options={"verbose_name_plural": "Chats app settings"},
        ),
    ]
