# Generated by Django 5.1.3 on 2024-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_grammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
