from adit_radis_shared.common.views import HtmxTemplateView
from django.urls import path

from .views import (
    ExtractionInstanceDetailView,
    ExtractionJobCancelView,
    ExtractionJobDeleteView,
    ExtractionJobDetailView,
    ExtractionJobListView,
    ExtractionJobRestartView,
    ExtractionJobResumeView,
    ExtractionJobRetryView,
    ExtractionJobVerifyView,
    ExtractionJobWizardView,
    ExtractionResultDownloadView,
    ExtractionResultListView,
    ExtractionTaskDeleteView,
    ExtractionTaskDetailView,
    ExtractionTaskResetView,
    ExtractionUpdatePreferencesView,
)

urlpatterns = [
    path(
        "update-preferences/",
        ExtractionUpdatePreferencesView.as_view(),
    ),
    path(
        "help/",
        HtmxTemplateView.as_view(template_name="extractions/_extraction_help.html"),
        name="extraction_help",
    ),
    path(
        "jobs/",
        ExtractionJobListView.as_view(),
        name="extraction_job_list",
    ),
    path(
        "jobs/new/",
        ExtractionJobWizardView.as_view(),
        name="extraction_job_create",
    ),
    path(
        "jobs/<int:pk>/",
        ExtractionJobDetailView.as_view(),
        name="extraction_job_detail",
    ),
    path(
        "jobs/<int:pk>/delete/",
        ExtractionJobDeleteView.as_view(),
        name="extraction_job_delete",
    ),
    path(
        "jobs/<int:pk>/verify/",
        ExtractionJobVerifyView.as_view(),
        name="extraction_job_verify",
    ),
    path(
        "jobs/<int:pk>/cancel/",
        ExtractionJobCancelView.as_view(),
        name="extraction_job_cancel",
    ),
    path(
        "jobs/<int:pk>/resume/",
        ExtractionJobResumeView.as_view(),
        name="extraction_job_resume",
    ),
    path(
        "jobs/<int:pk>/retry/",
        ExtractionJobRetryView.as_view(),
        name="extraction_job_retry",
    ),
    path(
        "jobs/<int:pk>/restart/",
        ExtractionJobRestartView.as_view(),
        name="extraction_job_restart",
    ),
    path(
        "jobs/<int:pk>/verify/",
        ExtractionJobVerifyView.as_view(),
        name="extraction_job_verify",
    ),
    path(
        "tasks/<int:pk>/",
        ExtractionTaskDetailView.as_view(),
        name="extraction_task_detail",
    ),
    path(
        "tasks/<int:pk>/delete/",
        ExtractionTaskDeleteView.as_view(),
        name="extraction_task_delete",
    ),
    path(
        "tasks/<int:pk>/reset/",
        ExtractionTaskResetView.as_view(),
        name="extraction_task_reset",
    ),
    path(
        "jobs/<int:pk>/results/",
        ExtractionResultListView.as_view(),
        name="extraction_result_list",
    ),
    path(
        "jobs/<int:pk>/results/download/",
        ExtractionResultDownloadView.as_view(),
        name="extraction_result_download",
    ),
    path(
        "instances/<int:pk>/",
        ExtractionInstanceDetailView.as_view(),
        name="extraction_instance_detail",
    ),
]
