x-app: &default-app
  volumes:
    - /mnt:/mnt
  depends_on:
    - postgres
  environment:
    USE_DOCKER: 1
    PROJECT_VERSION: ${PROJECT_VERSION:-vX.Y.Z}
    DATABASE_URL: "psql://postgres:postgres@postgres.local:5432/postgres"
    DJANGO_STATIC_ROOT: "/var/www/web/static/"
    LLAMACPP_URL: "http://llamacpp.local:8080"

services:
  init:
    <<: *default-app
    hostname: init.local
    volumes:
      - web_data:/var/www/web
      - /mnt:/mnt

  web:
    <<: *default-app
    hostname: web.local
    build:
      context: ..
    volumes:
      - web_data:/var/www/web
      - /mnt:/mnt

  worker_default:
    <<: *default-app
    hostname: worker_default.local

  worker_llm:
    <<: *default-app
    hostname: worker_llm.local

  postgres:
    image: postgres:17
    hostname: postgres.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  web_data:
  postgres_data:
