"""
Django settings for radis project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from pathlib import Path

from adit_radis_shared.telemetry import add_otel_logging_handler, is_telemetry_active
from django.core.exceptions import ImproperlyConfigured
from environs import env

from radis.core.utils.model_spec import ModelSpec, ModelSpecError, parse_model_spec

# During development and calling `manage.py` from the host we have to load the .env file manually.
# Some env variables will still need a default value, as those are only set in the compose file.
if not env.bool("IS_DOCKER_CONTAINER", default=False):
    env.read_env()

# The base directory of the project (the root of the repository)
BASE_PATH = Path(__file__).resolve(strict=True).parent.parent.parent

# The source paths of the project
SOURCE_PATHS = [BASE_PATH / "radis"]

# Fetch version from the environment which is passed through from the git version tag
PROJECT_VERSION = env.str("PROJECT_VERSION", default="v0.0.0")

# The project URL used in the navbar and footer
PROJECT_URL = "https://github.com/openradx/radis"

# Needed by sites framework
SITE_ID = 1

# The following settings are synced to the Site model of the sites framework on startup
# (see common/apps.py in adit-radis-shared).
SITE_DOMAIN = env.str("SITE_DOMAIN")
SITE_NAME = env.str("SITE_NAME")

SECRET_KEY = env.str("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

_stack_name = env.str("STACK_NAME", default="")
SESSION_COOKIE_NAME = f"sessionid_{_stack_name}" if _stack_name else "sessionid"
CSRF_COOKIE_NAME = f"csrftoken_{_stack_name}" if _stack_name else "csrftoken"

INSTALLED_APPS = [
    "daphne",
    "whitenoise.runserver_nostatic",
    "adit_radis_shared.common.apps.CommonConfig",
    "registration",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    "django.contrib.postgres",
    "django_extensions",
    "procrastinate.contrib.django",
    "dbbackup",
    "revproxy",
    "loginas",
    "django_cotton.apps.SimpleAppConfig",
    "block_fragments.apps.SimpleAppConfig",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_htmx",
    "django_tables2",
    "formtools",
    "rest_framework",
    "adrf",
    "markdownify",
    "radis.core.apps.CoreConfig",
    "adit_radis_shared.accounts.apps.AccountsConfig",
    "adit_radis_shared.token_authentication.apps.TokenAuthenticationConfig",
    "radis.reports.apps.ReportsConfig",
    "radis.search.apps.SearchConfig",
    "radis.extractions.apps.ExtractionsConfig",
    "radis.labels.apps.LabelsConfig",
    "radis.subscriptions.apps.SubscriptionsConfig",
    "radis.collections.apps.CollectionsConfig",
    "radis.notes.apps.NotesConfig",
    "radis.chats.apps.ChatsConfig",
    "radis.pgsearch.apps.PgSearchConfig",
    "channels",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "adit_radis_shared.accounts.middlewares.ActiveGroupMiddleware",
    "adit_radis_shared.common.middlewares.MaintenanceMiddleware",
]

ROOT_URLCONF = "radis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "OPTIONS": {
            "loaders": [
                (
                    "block_fragments.loader.Loader",
                    [
                        (
                            "django.template.loaders.cached.Loader",
                            [
                                "django_cotton.cotton_loader.Loader",
                                "django.template.loaders.filesystem.Loader",
                                "django.template.loaders.app_directories.Loader",
                            ],
                        )
                    ],
                )
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "adit_radis_shared.common.site.base_context_processor",
                "radis.reports.site.base_context_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "radis.wsgi.application"

ASGI_APPLICATION = "radis.asgi.application"

# This seems to be important for Cloud IDEs as CookieStorage does not work there.
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

# DATABASE_URL is only set in the compose file. For local development on the host
# we use the port from the .env file directly.
postgres_dev_port = env.int("POSTGRES_DEV_PORT", default=5432)
database_url = f"postgres://postgres:postgres@localhost:{postgres_dev_port}/postgres"
DATABASES = {"default": env.dj_db_url("DATABASE_URL", default=database_url)}

# pgsearch indexing tuning (bulk upsert/backfill)
PGSEARCH_BULK_INDEX_CHUNK_SIZE = env.int("PGSEARCH_BULK_INDEX_CHUNK_SIZE", default=5000)
PGSEARCH_BULK_INSERT_BATCH_SIZE = env.int("PGSEARCH_BULK_INSERT_BATCH_SIZE", default=1000)
PGSEARCH_SYNC_INDEXING = env.bool("PGSEARCH_SYNC_INDEXING", default=False)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# A custom authentication backend that supports a single currently active group.
AUTHENTICATION_BACKENDS = ["adit_radis_shared.accounts.backends.ActiveGroupModelBackend"]

# Where to redirect to after login
LOGIN_REDIRECT_URL = "home"

# Settings for django-registration-redux
REGISTRATION_FORM = "adit_radis_shared.accounts.forms.RegistrationForm"
ACCOUNT_ACTIVATION_DAYS = 14
REGISTRATION_OPEN = True

# The mailers available for sending email, overridden per environment.
MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "OPTIONS": {"host": "localhost", "port": 25},
    },
}

EMAIL_SUBJECT_PREFIX = "[RADIS] "

# An Email address used by the RADIS server to notify about finished jobs and
# management notifications.
SERVER_EMAIL = env.str("DJANGO_SERVER_EMAIL")
DEFAULT_FROM_EMAIL = SERVER_EMAIL

# A support Email address that is presented to the users where
# they can get support.
SUPPORT_EMAIL = env.str("SUPPORT_EMAIL")

# The Django server admins that will receive critical error notifications.
ADMINS = [env.str("DJANGO_ADMIN_EMAIL")]

# Used by django-registration-redux to send account approval emails to.
# It expects (name, address) pairs.
REGISTRATION_ADMINS = [(env.str("DJANGO_ADMIN_FULL_NAME"), env.str("DJANGO_ADMIN_EMAIL"))]

# All REST API requests must come from authenticated clients
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "adit_radis_shared.token_authentication.auth.RestTokenAuthentication",
    ],
}

# See following examples:
# https://github.com/django/django/blob/master/django/utils/log.py
# https://cheat.readthedocs.io/en/latest/django/logging.html
# https://stackoverflow.com/a/7045981/166229
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "simple": {
            "format": "[%(asctime)s] %(name)-12s %(levelname)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S %Z",
        },
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S %Z",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "mail_admins": {
            "level": "CRITICAL",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "loggers": {
        "radis": {
            "handlers": ["console", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
    "root": {"handlers": ["console"], "level": "ERROR"},
}

if is_telemetry_active():
    add_otel_logging_handler(LOGGING)

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

# TODO: We don't want use translations yet, but everything is hardcoded in English
USE_I18N = True

USE_TZ = True

TIME_ZONE = env.str("TIME_ZONE", default="UTC")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = "/static/"

# Additional (project wide) static files
STATICFILES_DIRS = (BASE_PATH / "radis" / "static",)

# For crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# django-templates2
DJANGO_TABLES2_TEMPLATE = "common/_django_tables2.html"

# The salt that is used for hashing new tokens in the token authentication app.
# Cave, changing the salt after some tokens were already generated makes them all invalid!
TOKEN_AUTHENTICATION_SALT = env.str("TOKEN_AUTHENTICATION_SALT")

# Django default storage and django-dbbackup
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "dbbackup": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": env.str("DBBACKUP_STORAGE_LOCATION", default="/tmp/backups-radis")},
    },
}
DBBACKUP_CLEANUP_KEEP = 30
BACKUP_ENABLED = env.bool("BACKUP_ENABLED", default=True)
BACKUP_CRON = env.str("BACKUP_CRON", default="0 3 * * *")

# Used by django-filter
FILTERS_EMPTY_CHOICE_LABEL = "Show All"

# LLM configuration
# The OpenAI-compatible endpoint all inference is sent to. Required, as RADIS ships no
# inference server of its own. An empty value is rejected as well, so a misconfigured
# deployment fails at startup instead of on the first LLM call.
LLM_BASE_URL = env.str("LLM_BASE_URL").strip()
if not LLM_BASE_URL:
    raise ImproperlyConfigured(
        "LLM_BASE_URL must point to an OpenAI-compatible endpoint, e.g. "
        "http://host.docker.internal:11434/v1 for a provider running on the Docker host."
    )
# Many self-hosted providers ignore the key, but the OpenAI client requires it to be set.
LLM_API_KEY = env.str("LLM_API_KEY", default="")


def _optional_env(name: str, parse, default):
    """Read an optional setting, treating a blank value as unset.

    A blank is what an `.env` line like `LLM_EXTRA_SETTING=` produces, and it means the
    same as leaving the line out. A value that will not parse is reported with the name
    of the variable at fault, which a bare ValueError from deep in this module would not
    give the reader.
    """
    raw = env.str(name, default="").strip()
    if not raw:
        return default
    try:
        return parse(raw)
    except Exception as err:
        # Name the variable: a bare "could not convert string to float" from deep inside
        # the settings module leaves the admin guessing which one is at fault.
        raise ImproperlyConfigured(f"Invalid {name}={raw!r}: {err}") from err


# How long a single LLM HTTP request may take before the client aborts it.
LLM_REQUEST_TIMEOUT_SECONDS = _optional_env("LLM_REQUEST_TIMEOUT_SECONDS", float, 60.0)

# The model each feature talks to, as 'model[?param=value&...]'. The parameters are merged
# into the request body, so both standard OpenAI fields (temperature) and provider
# extensions (reasoning_effort, or vLLM's chat_template_kwargs.enable_thinking) can be set
# per model. Every feature falls back to LLM_DEFAULT_MODEL when its own is not configured.
LLM_FEATURES = ("chats", "query_generation", "extractions", "subscriptions", "labeling")


def _resolve_llm_models() -> dict[str, ModelSpec]:
    try:
        default = parse_model_spec(env.str("LLM_DEFAULT_MODEL"))
    except ModelSpecError as err:
        raise ImproperlyConfigured(f"Invalid LLM_DEFAULT_MODEL: {err}") from err

    models = {}
    for feature in LLM_FEATURES:
        name = f"LLM_{feature.upper()}_MODEL"
        raw = env.str(name, default="").strip()
        if not raw:
            models[feature] = default
            continue
        try:
            models[feature] = parse_model_spec(raw)
        except ModelSpecError as err:
            raise ImproperlyConfigured(f"Invalid {name}: {err}") from err
    return models


LLM_MODELS = _resolve_llm_models()

# Rate-limit gate: one per-process backoff window shared by every LLM client. On a 429
# it closes the gate so all callers back off together instead of hammering the provider.
#
# First step of the exponential backoff ladder used when the provider sends no Retry-After
# header (or an absurd one, see HEADER_CEILING). Doubles each consecutive 429: 2, 4, 8...
LLM_RATE_LIMIT_BACKOFF_BASE_SECONDS = env.float("LLM_RATE_LIMIT_BACKOFF_BASE_SECONDS", default=2.0)
# Upper cap on that exponential backoff pause, so the ladder never climbs past this.
LLM_RATE_LIMIT_BACKOFF_MAX_SECONDS = env.float("LLM_RATE_LIMIT_BACKOFF_MAX_SECONDS", default=120.0)

# Per-call wait budgets: how long a call may sit behind the gate before it is deferred.
# Long for background batch jobs (extractions), short for interactive chat where a user waits.
LLM_RATE_LIMIT_MAX_WAIT_SECONDS = env.float("LLM_RATE_LIMIT_MAX_WAIT_SECONDS", default=300.0)
LLM_RATE_LIMIT_INTERACTIVE_MAX_WAIT_SECONDS = env.float(
    "LLM_RATE_LIMIT_INTERACTIVE_MAX_WAIT_SECONDS", default=20.0
)

# Local retries for transient, per-request errors (connection drops, 5xx) — not 429s, which
# the gate owns. Retries this many times with an exponential delay starting at the base.
LLM_TRANSIENT_RETRY_ATTEMPTS = env.int("LLM_TRANSIENT_RETRY_ATTEMPTS", default=2)
LLM_TRANSIENT_RETRY_BASE_SECONDS = env.float("LLM_TRANSIENT_RETRY_BASE_SECONDS", default=1.0)

# A Retry-After below this is trusted and honored verbatim. At or above it, the header is
# treated as absurd and ignored, falling back to the exponential backoff ladder instead.
LLM_RATE_LIMIT_HEADER_CEILING_SECONDS = env.float(
    "LLM_RATE_LIMIT_HEADER_CEILING_SECONDS", default=1800.0
)


# Embedding service (per-deployment)
#
# Embeddings are inference too, but a different model class. One endpoint serves both
# only when the provider multiplexes models (OpenAI, Ollama, an LLM gateway); a
# self-hosted vLLM or SGLang serves one model per process, so there the embedding
# endpoint is a second URL. Inherit the LLM endpoint and override only where they
# actually diverge, so the common deployment configures one URL rather than two.
def _inherit_env(name: str, fallback: str) -> str:
    """An embedding setting that falls back to its LLM counterpart when unset.

    A blank is what an `.env` line like `EMBEDDINGS_BASE_URL=` produces, and it means
    the same as leaving the line out.
    """
    return env.str(name, default="").strip() or fallback


EMBEDDINGS_BASE_URL = _inherit_env("EMBEDDINGS_BASE_URL", LLM_BASE_URL)
EMBEDDINGS_API_KEY = _inherit_env("EMBEDDINGS_API_KEY", LLM_API_KEY)
EMBEDDINGS_REQUEST_TIMEOUT_SECONDS = _optional_env(
    "EMBEDDINGS_REQUEST_TIMEOUT_SECONDS", float, LLM_REQUEST_TIMEOUT_SECONDS
)


def _resolve_embeddings_model() -> ModelSpec | None:
    """The embedding model, or None when hybrid search is not configured.

    Unlike the LLM models this one is optional: without it RADIS serves full-text
    search only, which is a complete product rather than a broken one. That makes the
    model the feature switch — every embedding code path asks this one question
    instead of inferring configuredness from a URL that now has a fallback anyway.

    Same 'model[?param=value&...]' grammar as the LLM models, so request-body
    parameters (OpenAI's `dimensions`, a provider's `truncate`) are configured
    alongside the model. Parsed here so a malformed spec is a boot error naming the
    setting at fault, not a 400 on the first search.
    """
    raw = env.str("EMBEDDINGS_MODEL", default="").strip()
    if not raw:
        return None
    try:
        return parse_model_spec(raw)
    except ModelSpecError as err:
        raise ImproperlyConfigured(f"Invalid EMBEDDINGS_MODEL: {err}") from err


EMBEDDINGS_MODEL = _resolve_embeddings_model()

EMBEDDINGS_DIM = env.int("EMBEDDINGS_DIM", default=1024)

EMBEDDINGS_QUERY_INSTRUCTION = env.str(
    "EMBEDDINGS_QUERY_INSTRUCTION",
    default=(
        "Instruct: Given a radiology search query, retrieve relevant radiology reports.\nQuery: "
    ),
)

# Embedding tuning constants
# Texts per HTTP call. A 429'd or timed-out call wastes its whole payload
# and retries every text in it, so smaller batches bound the waste and
# consume the gateway's sliding window in smoother increments.
EMBEDDINGS_BATCH_SIZE = env.int("EMBEDDINGS_BATCH_SIZE", default=200)
# Reports per Procrastinate subjob (task granularity, not HTTP granularity).
EMBEDDINGS_SUBJOB_SIZE = env.int("EMBEDDINGS_SUBJOB_SIZE", default=1000)
# Procrastinate task priorities for the `embeddings` queue. Live writes
# (write-path handler + FTS chain) get LIVE; operator-initiated backfill
# (`embed_pending`, admin action) gets BACKFILL. A million-row backfill
# parks itself ahead of every later live write without this split.
EMBEDDINGS_LIVE_PRIORITY = 1
EMBEDDINGS_BACKFILL_PRIORITY = 0
# How long a search query's embedding stays in the Django cache. Paginating re-runs the
# whole search per page, so this is what keeps page 2..n from re-calling the embedding
# service for the same query text. Vectors are tiny (~8 KB) and deterministic per model
# config, so the TTL only bounds staleness across model/config changes, not correctness.
EMBEDDINGS_QUERY_CACHE_TIMEOUT_SECONDS = env.int(
    "EMBEDDINGS_QUERY_CACHE_TIMEOUT_SECONDS", default=900
)
# Rate-limit gate for the embedding provider: one per-process backoff window shared by
# every embedding caller in the process (mirrors the LLM gate in core.utils.llm_client).
# The embedding gateway is a different provider than the LLM, so it gets its own gate —
# a 429 from one must not pause the other. Semantics of each knob match the LLM_RATE_LIMIT_*
# settings above.
EMBEDDINGS_RATE_LIMIT_BACKOFF_BASE_SECONDS = 2.0
EMBEDDINGS_RATE_LIMIT_BACKOFF_MAX_SECONDS = 120.0
EMBEDDINGS_RATE_LIMIT_HEADER_CEILING_SECONDS = 1800.0
# Wait budgets: long for background embedding tasks; short for the search path, where a
# user is waiting and falling back to FTS-only beats hanging on a closed gate.
EMBEDDINGS_RATE_LIMIT_MAX_WAIT_SECONDS = 300.0
EMBEDDINGS_RATE_LIMIT_QUERY_MAX_WAIT_SECONDS = 10.0
# Local retries of transient (non-429) embedding call failures, mirroring the
# LLM_TRANSIENT_RETRY_* knobs above: N retries after the first call, with
# exponential backoff base * 2**attempt (0.5s, 1s).
EMBEDDINGS_TRANSIENT_RETRY_ATTEMPTS = 2
EMBEDDINGS_TRANSIENT_RETRY_BASE_SECONDS = 0.5
# Procrastinate-level retry of a whole embedding subjob (see
# EMBEDDING_TASK_RETRY_STRATEGY in radis.pgsearch.tasks). Waits grow as
# exponential_wait ** attempt: 6s, 36s, ~4min, ~22min.
EMBEDDINGS_TASK_MAX_ATTEMPTS = 5
EMBEDDINGS_TASK_EXPONENTIAL_WAIT_SECONDS = 6

# Hybrid search tuning
HYBRID_VECTOR_TOP_K = 100
HYBRID_FTS_MAX_RESULTS = 10_000
HYBRID_RRF_K = 60

# Chat
CHAT_GENERATE_TITLE_SYSTEM_PROMPT = """
Summarize the following conversation in $num_words words or less and in the same language as
the conversation. Be concise and don't hallucinate.

User:
$user_prompt

Assistant:
$assistant_response
"""

CHAT_GENERAL_SYSTEM_PROMPT = """
You are an AI medical assistant with extensive knowledge in radiology and general medicine.
You have been trained on a wide range of medical literature, including the latest research
and guidelines in radiological practices.
You wil discuss and answer various questions about radiology and general medicine.
Provide concise, well-structured answers in the same language used in the question. Do use
appropriate medical terminology. Use headers to organize information when necessary. Include
relevant anatomical details, imaging modalities, and diagnostic considerations where applicable.
Base your responses on current, peer-reviewed medical literature and established radiological
guidelines. If there are conflicting views or ongoing debates in the field, acknowledge them
briefly.
"""

CHAT_REPORT_SYSTEM_PROMPT = """
You are an AI medical assistant with extensive knowledge in radiology and general medicine.
You have been trained on a wide range of medical literature, including the latest research
and guidelines in radiological practices.
You will be asked questions about a radiology report that you have to answer. The report and
question can be given in any language.
Provide short, concise and well-structured answers in the same language used in the question.
Do use appropriate medical terminology. Use headers to organize information when necessary.
Include relevant anatomical details, imaging modalities, and diagnostic considerations where
applicable. Base your responses on current, peer-reviewed medical literature and established
radiological guidelines. If there are conflicting views or ongoing debates in the field,
acknowledge them briefly. Don't make up new data that is not mentioned in the report and
don't hallucinate.

Report:
$report
"""

# Subscription
SUBSCRIPTION_FILTER_PROMPT = """
You are an AI medical assistant with extensive knowledge in radiology and general medicine.
You have been trained on a wide range of medical literature, including the latest research
and guidelines in radiological practices.
Answer the following filter questions about the radiology report. The questions can be in any
language. Base your answers strictly on the contents of the report. Return the answers in JSON
format using the provided field identifiers. Answer with `true` for "yes" and `false` for "no".

Radiology Report:
$report

Questions:
$questions

"""

SUBSCRIPTION_EXTRACTION_PROMPT = """
You are an AI medical assistant with extensive knowledge in radiology and general medicine.
Extract the requested information from the radiology report. Only provide data that is explicitly
mentioned in the report and respect the expected data type. If the report does not contain the
requested information, respond with null. Return the extracted information in JSON format using
the provided field identifiers.

Radiology Report:
$report

Fields to extract:
$fields
"""

# Extraction
OUTPUT_FIELDS_SYSTEM_PROMPT = """
You are an AI medical assistant with extensive knowledge in radiology and general medicine.
You have been trained on a wide range of medical literature, including the latest research
and guidelines in radiological practices.
Extract the following information from the given radiology report by using the below field
definitions. The report and fields can be given in any language.
Only provide data that is really found in the report. Don't make up new data and don't hallucinate.
Return the extracted information in JSON format.

Radiology Report:
$report

Fields to extract:
$fields
"""

# Query Generation from Extraction Fields
ENABLE_AUTO_QUERY_GENERATION = env.bool("ENABLE_AUTO_QUERY_GENERATION", default=True)
# A user waits on this one, so it is much shorter than the worker timeout. It replaces
# LLM_REQUEST_TIMEOUT_SECONDS rather than capping it, so a slow endpoint needs this raised
# as well — see https://github.com/openradx/radis/issues/266.
QUERY_GENERATION_TIMEOUT = _optional_env("QUERY_GENERATION_TIMEOUT", int, 10)
QUERY_GENERATION_MAX_RETRIES = env.int("QUERY_GENERATION_MAX_RETRIES", default=2)

QUERY_GENERATION_SYSTEM_PROMPT = """You are an AI assistant specialized in medical informatics and
radiology report retrieval. Your task is to generate an effective search query to find radiology
reports that would contain information relevant to the specified data extraction fields.
Given extraction fields with their descriptions and types, generate a boolean search query that
will retrieve reports likely to contain the requested information.

Guidelines:
1. Use medical terminology and common synonyms
2. Prefer broader terms to avoid missing relevant reports
3. Use boolean operators: AND, OR, NOT
4. Use quotes for exact phrases: "lung nodule"
5. Consider anatomical variations and medical abbreviations
6. Keep the query concise but comprehensive (max 150 characters recommended)
7. Focus on key concepts that would appear in reports containing this data

Output format: Return ONLY the search query as a single line, without explanation.

Examples:
Fields: [{"name": "nodule_size", "description": "size of lung nodule in millimeters",
"type": "NUMERIC"}]
Query: ("lung nodule" OR "pulmonary nodule") AND (size OR measurement OR diameter)

Fields: [{"name": "fracture_type", "description": "type of bone fracture", "type": "TEXT"},
{"name": "bone", "description": "which bone is fractured", "type": "TEXT"}]
Query: fracture AND bone

Extraction Fields:
$fields

Generate the search query:"""

# The maximum number of reports that can be extracted by one extraction job.
EXTRACTION_MAXIMUM_REPORTS_COUNT = 25000

# The maximum number of enumerated options a Selection output field may define.
EXTRACTION_MAX_SELECTION_OPTIONS = 7

# The default and urgent priorities for extraction tasks.
EXTRACTION_DEFAULT_PRIORITY = 2
EXTRACTION_URGENT_PRIORITY = 3

# The number of extraction instances that are processed within one extraction task.
EXTRACTION_TASK_BATCH_SIZE = 100

# The number of parallel requests the LLM can handle. This limit is enforced within each task. When
# having multiple workers that uses the LLM, the total number of parallel requests is
# EXTRACTION_LLM_CONCURRENCY_LIMIT * number of workers. Keep this within whatever concurrency the
# configured provider allows, otherwise the surplus requests just get rate limited.
EXTRACTION_LLM_CONCURRENCY_LIMIT = 6

START_EXTRACTION_JOB_UNVERIFIED = False

# Subscription
SUBSCRIPTION_DEFAULT_PRIORITY = 3
SUBSCRIPTION_URGENT_PRIORITY = 4
SUBSCRIPTION_CRON = "0 * * * *"  # Refresh subscriptions at the top of every hour
SUBSCRIPTION_REFRESH_TASK_BATCH_SIZE = 100

# Labeling (radis.labels)
# Generic prompt: label-specific text rides in each schema field's description; only $report
# is substituted.
_DEFAULT_LABELING_SYSTEM_PROMPT = """
You are an AI medical assistant. The provided schema lists one field per label, each
field's description defining the label. For every field, decide how strongly the report
below supports that label, choosing exactly one of:
  - "PRESENT"     — the report clearly states this is present
  - "LIKELY"      — the report strongly suggests it, without stating it outright
  - "POSSIBLE"    — the report leaves it as a possibility / cannot be excluded
  - "ABSENT"      — the report explicitly states this is not present
  - "UNMENTIONED" — the report does not address this at all

Return answers in JSON format matching the provided schema.

Radiology Report:
$report
"""

# Generic gate (Yes/No applicability) system prompt. Only $report is substituted.
_DEFAULT_GATE_SYSTEM_PROMPT = """
You are an AI medical assistant. The provided schema lists one field per topic, each
field's description stating the topic's screening question. For every field, answer
whether the radiology report below contains content relevant to that topic, responding
with exactly one of:
  - "YES" — the report clearly contains relevant content
  - "NO"  — the report clearly does not

Return answers in JSON format matching the provided schema.

Radiology Report:
$report
"""

LABELING_SYSTEM_PROMPT = env.str("LABELING_SYSTEM_PROMPT", default=_DEFAULT_LABELING_SYSTEM_PROMPT)
LABELING_GATE_SYSTEM_PROMPT = env.str(
    "LABELING_GATE_SYSTEM_PROMPT", default=_DEFAULT_GATE_SYSTEM_PROMPT
)

# Scan and manual backfill share one priority (only one LabelingJob runs at a time).
LABELING_JOB_PRIORITY = env.int("LABELING_JOB_PRIORITY", default=1)

LABELING_TASK_BATCH_SIZE = env.int("LABELING_TASK_BATCH_SIZE", default=100)
LABELING_LLM_CONCURRENCY_LIMIT = env.int("LABELING_LLM_CONCURRENCY_LIMIT", default=2)
LABELING_GATE_BATCH_SIZE = env.int("LABELING_GATE_BATCH_SIZE", default=10)

# Cron schedule for the periodic incremental scan (default: daily at 2 AM).
LABELING_SCAN_CRON = env.str("LABELING_SCAN_CRON", default="0 2 * * *")

# The priority for stalled jobs that are retried.
STALLED_JOBS_RETRY_PRIORITY = 10

# Heartbeat silence before a worker counts as dead when repairing stale analysis tasks.
# Never set below 30 — Procrastinate itself declares workers stalled at 30 s.
ANALYSIS_STALLED_WORKER_GRACE_SECONDS = env.int("ANALYSIS_STALLED_WORKER_GRACE_SECONDS", default=30)

# Cron for the periodic sweep that repairs tasks left IN_PROGRESS by killed workers.
ANALYSIS_SWEEP_CRON = env.str("ANALYSIS_SWEEP_CRON", default="* * * * *")
