# Generated by Django 4.2.10 on 2024-02-24 00:47

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import radis.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=128, unique=True)),
                ('language', models.CharField(max_length=10)),
                ('pacs_aet', models.CharField(max_length=16)),
                ('pacs_name', models.CharField(max_length=64)),
                ('patient_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid wildcard characters.', regex='[\\*\\?]')])),
                ('patient_birth_date', models.DateField()),
                ('patient_sex', models.CharField(max_length=1, validators=[radis.core.validators.validate_patient_sex])),
                ('study_description', models.CharField(blank=True, max_length=64)),
                ('study_datetime', models.DateTimeField()),
                ('modalities_in_study', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), size=None)),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(default=dict, validators=[radis.core.validators.validate_metadata])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='reports', to='auth.group')),
            ],
        ),
    ]
