# Generated by Django 5.1.4 on 2025-01-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SubscriptionAppSettings",
            new_name="SubscriptionsAppSettings",
        ),
    ]
