# Generated by Django 5.1.4 on 2025-01-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0002_rename_subscriptionappsettings_subscriptionsappsettings",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionsappsettings",
            options={"verbose_name_plural": "Subscriptions app settings"},
        ),
    ]
