# Generated by Django 5.1.6 on 2025-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_questionfield_delete_filterfield_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionfield",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="questionfield",
            name="question",
            field=models.CharField(max_length=300),
        ),
    ]
