# Generated by Django 5.2.7 on 2025-11-03 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0008_rename_filter_fields_result_subscribeditem_answers_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question",
            new_name="FilterQuestion",
        ),
        migrations.AddField(
            model_name="filterquestion",
            name="expected_answer",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")],
                default="Y",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="filterquestion",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filter_questions",
                to="subscriptions.subscription",
            ),
        ),
        migrations.RenameField(
            model_name="subscribeditem",
            old_name="answers",
            new_name="filter_results",
        ),
        migrations.AddField(
            model_name="subscribeditem",
            name="extraction_results",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
