# Generated by Django 5.2.7 on 2025-11-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0008_rename_filter_fields_result_subscribeditem_answers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribeditem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-created_at"]},
        ),
    ]
