# Generated by Django 5.2.7 on 2025-11-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0008_rename_filter_fields_result_subscribeditem_answers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribeditem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="subscribeditem",
            old_name="answers",
            new_name="extraction_results",
        ),
        migrations.AddField(
            model_name="subscribeditem",
            name="filter_results",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FilterQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                (
                    "expected_answer",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=1
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_questions",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
