# Generated by Django 5.2.8 on 2025-11-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0009_alter_subscribeditem_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="provider",
        ),
    ]
