# Generated by Django 5.1.6 on 2025-11-19 08:51

from django.db import migrations

from adit_radis_shared.common.utils.migration_utils import procrastinate_on_delete_sql

class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_rename_answers_subscribeditem_filter_results_and_more"),
        ("procrastinate", "0028_add_cancel_states"),
    ]

    operations = [
        migrations.RunSQL(
            sql=procrastinate_on_delete_sql("subscriptions", "subscriptionjob"),
            reverse_sql=procrastinate_on_delete_sql("subscriptions", "subscriptionjob", reverse=True),
        ),
        migrations.RunSQL(
            sql=procrastinate_on_delete_sql("subscriptions", "subscriptiontask"),
            reverse_sql=procrastinate_on_delete_sql("subscriptions", "subscriptiontask", reverse=True),
        ),
    ]
