# Generated by Django 5.2.8 on 2025-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_procrastinate_on_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
