# Generated by Django 5.2.8 on 2025-12-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_subscription_last_viewed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="query",
        ),
    ]
