# Generated by Django 4.2.10 on 2024-02-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_squashed_0003_remove_report_institutes_report_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='references',
            new_name='links',
        ),
    ]
