# Generated by Django 4.2.10 on 2024-02-15 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_references_report_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
    ]
