# Generated by Django 4.2.10 on 2024-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(default='en', max_length=10),
            preserve_default=False,
        ),
    ]
