# Generated by Django 4.2.10 on 2024-03-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_accession_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('filterable', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Modalities',
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='report',
            name='modalities_in_study',
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='reports.report')),
            ],
            options={
                'verbose_name_plural': 'Metadata',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='modalities',
            field=models.ManyToManyField(related_name='reports', to='reports.modality'),
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(fields=('report', 'key'), name='unique_key_per_report'),
        ),
    ]
