# Generated by Django 5.0.4 on 2024-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_language_alter_report_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='links',
        ),
        migrations.AddField(
            model_name='report',
            name='pacs_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
