# Generated by Django 5.0.7 on 2024-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_report_links_report_pacs_link'),
    ]

    operations = [
        # Postgres needs some immutable function for the age calculation
        migrations.RunSQL("""
        CREATE OR REPLACE FUNCTION calc_age( study_datetime timestamp with time zone, patient_birth_date date )
        RETURNS integer
        AS $CODE$
        BEGIN
            RETURN EXTRACT(YEAR FROM age(study_datetime, patient_birth_date::timestamp));
        END
        $CODE$
        LANGUAGE plpgsql IMMUTABLE;
        """, reverse_sql="""
        DROP FUNCTION calc_age(timestamp with time zone, date);
        """),
        migrations.AddField(
            model_name='report',
            name='patient_age',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.Func(models.F('study_datetime'), models.F('patient_birth_date'), function='calc_age'), output_field=models.IntegerField()), output_field=models.IntegerField()),
        ),
    ]
