# Generated by Django 5.0.6 on 2024-07-10 10:36

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_remove_report_links_report_pacs_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
