# Generated by Django 5.1 on 2024-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_report_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accession_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='report',
            name='study_instance_uid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
