# Generated by Django 5.2.7 on 2025-11-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_report_accession_number_and_study_instance_uid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={"ordering": ["-created_at", "document_id"]},
        ),
    ]
