# Generated by Django 5.1 on 2024-11-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_report_accession_number_and_study_instance_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="body_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="body_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
