# Generated by Django 6.0.1 on 2026-01-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportOverviewTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_overview_total', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='ReportLanguageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_language_stats', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'language_code'), name='unique_report_language_stat')],
            },
        ),
        migrations.CreateModel(
            name='ReportModalityStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_code', models.CharField(max_length=16)),
                ('count', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_modality_stats', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'modality_code'), name='unique_report_modality_stat')],
            },
        ),
        migrations.CreateModel(
            name='ReportYearStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_year_stats', to='auth.group')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('group', 'year'), name='unique_report_year_stat')],
            },
        ),
    ]
