# Generated by Django 6.0.7 on 2026-09-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_report_withdrawn_partial_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawnReport',
            fields=[
            ],
            options={
                'verbose_name': 'Withdrawn report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reports.report',),
        ),
    ]
