# Generated by Django 5.0.7 on 2024-08-03 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inbox_inboxitem_refreshinboxjob_refreshinboxtask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
