# Generated by Django 5.0.7 on 2024-08-04 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_inbox_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
