# Generated by Django 5.0.7 on 2024-08-04 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inbox', '0004_inbox_created_at'),
        ('reports', '0011_report_patient_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='title',
            new_name='name',
        ),
        migrations.AddConstraint(
            model_name='inbox',
            constraint=models.UniqueConstraint(fields=('name', 'owner_id'), name='unique_inbox_name_per_user'),
        ),
    ]
