# Generated by Django 4.2.9 on 2024-02-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VespaReFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("IP", "In Progress"),
                            ("SU", "Success"),
                            ("FA", "Failure"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("log", models.TextField(blank=True, default="")),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("progress_count", models.PositiveIntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("started", models.DateTimeField(blank=True, null=True)),
                ("ended", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created"], name="vespa_vespa_created_fc3037_idx"),
                    models.Index(fields=["status"], name="vespa_vespa_status_6549f2_idx"),
                ],
            },
        ),
    ]
