# Generated by Django 6.0.1 on 2026-06-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0013_alter_report_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("gate_question", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="labels.labelgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No"), ("MAYBE", "Maybe")],
                        max_length=5,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_answers",
                        to="reports.report",
                    ),
                ),
                (
                    "label_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_answers",
                        to="labels.labelgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelingScanCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Labeling scan checkpoint",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="singleton_labeling_scan_checkpoint",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LIKELY", "Likely"),
                            ("POSSIBLE", "Possible"),
                            ("ABSENT", "Absent"),
                            ("UNMENTIONED", "Unmentioned"),
                        ],
                        max_length=11,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="labels.label",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_results",
                        to="reports.report",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["active"], name="labels_labe_active_6904ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_label_name"
            ),
        ),
        migrations.AddIndex(
            model_name="gateanswer",
            index=models.Index(
                fields=["label_group", "value"], name="labels_gate_label_g_b4f68c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gateanswer",
            constraint=models.UniqueConstraint(
                fields=("report", "label_group"),
                name="unique_gate_answer_per_report_group",
            ),
        ),
        migrations.AddIndex(
            model_name="labelresult",
            index=models.Index(
                fields=["label", "value"], name="labels_labe_label_i_fbb052_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelresult",
            index=models.Index(
                fields=["report"], name="labels_labe_report__2243fe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labelresult",
            constraint=models.UniqueConstraint(
                fields=("report", "label"), name="unique_result_per_report_label"
            ),
        ),
    ]
