# Generated by Django 6.0.1 on 2026-05-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("label", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active", "group"], name="labels_ques_active_9ac817_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("label",), name="unique_question_label"
                    )
                ],
            },
        ),
    ]
