# Generated by Django 6.0.1 on 2026-06-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("procrastinate", "0041_post_retry_failed_job"),
        ("reports", "0013_alter_report_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("gate_question", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="labels.labelgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[("YES", "Yes"), ("NO", "No"), ("MAYBE", "Maybe")],
                        max_length=5,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_answers",
                        to="reports.report",
                    ),
                ),
                (
                    "label_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_answers",
                        to="labels.labelgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabelingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UV", "Unverified"),
                            ("PR", "Preparing"),
                            ("PE", "Pending"),
                            ("IP", "In Progress"),
                            ("CI", "Canceling"),
                            ("CA", "Canceled"),
                            ("SU", "Success"),
                            ("WA", "Warning"),
                            ("FA", "Failure"),
                        ],
                        default="UV",
                        max_length=2,
                    ),
                ),
                ("urgent", models.BooleanField(default=False)),
                ("send_finished_mail", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("SCAN", "Periodic scan"),
                            ("MANUAL", "Manual backfill"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("scan_from", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "queued_job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procrastinate.procrastinatejob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabelingScanCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Labeling scan checkpoint",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="singleton_labeling_scan_checkpoint",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabelingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("IP", "In Progress"),
                            ("CA", "Canceled"),
                            ("SU", "Success"),
                            ("WA", "Warning"),
                            ("FA", "Failure"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("log", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="labels.labelingjob",
                    ),
                ),
                (
                    "queued_job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procrastinate.procrastinatejob",
                    ),
                ),
                (
                    "reports",
                    models.ManyToManyField(related_name="+", to="reports.report"),
                ),
            ],
            options={
                "ordering": ("id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabelResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("LIKELY", "Likely"),
                            ("POSSIBLE", "Possible"),
                            ("ABSENT", "Absent"),
                            ("UNMENTIONED", "Unmentioned"),
                        ],
                        max_length=11,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="labels.label",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_results",
                        to="reports.report",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="label",
            index=models.Index(fields=["active"], name="labels_labe_active_6904ba_idx"),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_label_name"
            ),
        ),
        migrations.AddIndex(
            model_name="gateanswer",
            index=models.Index(
                fields=["label_group", "value"], name="labels_gate_label_g_b4f68c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gateanswer",
            constraint=models.UniqueConstraint(
                fields=("report", "label_group"),
                name="unique_gate_answer_per_report_group",
            ),
        ),
        migrations.AddIndex(
            model_name="labelresult",
            index=models.Index(
                fields=["label", "value"], name="labels_labe_label_i_fbb052_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labelresult",
            index=models.Index(
                fields=["report"], name="labels_labe_report__2243fe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="labelresult",
            constraint=models.UniqueConstraint(
                fields=("report", "label"), name="unique_result_per_report_label"
            ),
        ),
    ]
