# Generated by Django 6.0.1 on 2026-02-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelquestion',
            name='description',
        ),
    ]
