# Generated by Django 6.0.1 on 2026-05-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('reports', '0013_alter_report_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], max_length=5)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='labels.question')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.report')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'value'], name='labels_answ_questio_dacba3_idx'), models.Index(fields=['report'], name='labels_answ_report__36b5e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'question'), name='unique_answer_per_report_question')],
            },
        ),
    ]
