# Generated by Django 6.0.1 on 2026-02-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_remove_labelquestion_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelquestion',
            options={'ordering': ['order', 'question']},
        ),
        migrations.RemoveConstraint(
            model_name='labelquestion',
            name='unique_label_question_name_per_group',
        ),
        migrations.AddConstraint(
            model_name='labelquestion',
            constraint=models.UniqueConstraint(fields=('group', 'question'), name='unique_label_question_per_group'),
        ),
        migrations.RemoveField(
            model_name='labelquestion',
            name='name',
        ),
    ]
