# Generated by Codex on 2026-02-08

from django.db import migrations, models


def populate_label_from_question(apps, schema_editor):
    LabelQuestion = apps.get_model("labels", "LabelQuestion")
    LabelQuestion.objects.filter(label="").update(label=models.F("question"))


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0003_alter_labelquestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelquestion",
            name="label",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(populate_label_from_question, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="labelquestion",
            name="unique_label_question_per_group",
        ),
        migrations.AddConstraint(
            model_name="labelquestion",
            constraint=models.UniqueConstraint(
                fields=("group", "label"),
                name="unique_label_question_label_per_group",
            ),
        ),
        migrations.AlterModelOptions(
            name="labelquestion",
            options={"ordering": ["order", "label"]},
        ),
    ]
